version: '3'

services:
  # master 01
  es-master-01:
    image: elasticsearch:7.2.0
    container_name: es-master-01
    environment:
      - node.name=es-master-01
      - discovery.seed_hosts=es-master-01,es-slave-01,es-slave-02
      - cluster.initial_master_nodes=es-master-01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - indices.fielddata.cache.size=20%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC -XX:-UseCMSInitiatingOccupancyOnly -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=75"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-es-master-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  # slave 1
  es-slave-01:
    image: elasticsearch:7.2.0
    container_name: es-slave-01
    environment:
      - node.name=es-slave-01
      - discovery.seed_hosts=es-master-01,es-slave-01,es-slave-02
      - cluster.initial_master_nodes=es-master-01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - indices.fielddata.cache.size=20%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC -XX:-UseCMSInitiatingOccupancyOnly -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=75"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-es-slave-01:/usr/share/elasticsearch/data
    networks:
      - esnet

  # slave 2
  es-slave-02:
    image: elasticsearch:7.2.0
    container_name: es-slave-02
    environment:
      - node.name=es-slave-02
      - discovery.seed_hosts=es-master-01,es-slave-01,es-slave-02
      - cluster.initial_master_nodes=es-master-01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - indices.fielddata.cache.size=20%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC -XX:-UseCMSInitiatingOccupancyOnly -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=75"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-es-slave-02:/usr/share/elasticsearch/data
    networks:
      - esnet

  # kibana
  kibana:
    image: kibana:7.2.0
    depends_on:
      - es-master-01
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es-master-01:9200
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  data-es-master-01:
    driver: local
  data-es-slave-01:
    driver: local
  data-es-slave-02:
    driver: local

networks:
  esnet:
