version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - data-mysql:/usr/share/elasticsearch/data
    ports:
      - 3306:3306
      - 33060:33060
    # networks:
    #   - mysql-net
volumes:
  data-mysql:

# networks:
#   mysql-net: