version: '3'

services:
  tensorflow:
    image: tensorflow/tensorflow
    user: "${UID}:${GID}"
    container_name: tensorflow
    volumes:
      - data-tensorflow:/tmp
    ports:
      - 8888:8888
    # networks:
    #   - redis-net
volumes:
  data-tensorflow:
    driver: local

# networks:
#   esnet: